name: PR_Test

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Download
        run: go mod download

      - name: Build
        run: go build -v -o app ./...

      - name: Test
        run: go test -cover -race ./...
