name: Scheduled
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build-test-deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Downloada
        run: go mod download

      - name: Builds
        run: GOOS=linux GOARCH=arm64 go build -v -o app ./...

      - name: Test
        run: go test -cover -race ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Login to Google Container Registry
        uses: ./
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build docker image
        run:  docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-service:latest . 

      - name: Push to Google Container Registry
        run:  docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-service:latest 

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/service:latest
          service: hello-service
